# Site settings
title: crb
myname: Christopher Brull
email: chris@brull.me
description: > # this means to ignore newlines until "baseurl:"
  A collection of notes and thoughts that might otherwise get lost...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.brull.me" # the base hostname & protocol for your site
twitter_username: kujhawk94
github_username: kujhawk94

# Build settings
markdown: kramdown 
